"""add site subreddits column

Revision ID: 3901270268eb
Revises: 97de4f113d28
Create Date: 2026-09-03 15:47:32.594922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3901270268eb'
down_revision: Union[str, None] = '97de4f113d28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('subreddits', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'subreddits')
    # ### end Alembic commands ###
