"""fix article outline column to json, add site subreddits

Revision ID: b431cbd45470
Revises: 3901270268eb
Create Date: 2026-09-03 16:02:26.064643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b431cbd45470'
down_revision: Union[str, None] = '3901270268eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'outline',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='outline::json')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'outline',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True,
               postgresql_using='outline::text')
    # ### end Alembic commands ###
